---
sudo: required
language: python
python:
  - "3.6"
services:
  - docker
before_install:
  - sudo apt-get -qq update
install:
  - pip install molecule
  - pip install docker
script:
  - molecule test
